<?php
define('PAGE_TITLE', 'Welcome');
require_once 'includes/config.php';
include 'includes/header.php';
?>

<style>
    .hero {
        background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=2575&auto=format&fit=crop') no-repeat center center/cover;
        color: white;
    }
</style>

<div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3 hero">
        <h1 class="text-warning display-4 fw-bold">Unlock Your Inner Strength</h1>
        <p class="col-lg-8 mx-auto fs-5 text-light">
            Join KP Fitness and transform your fitness journey with our comprehensive class reservation system, expert trainers, and state-of-the-art facilities.
        </p>
        <div class="d-inline-flex gap-2 mb-5">
            <a href="<?php echo SITE_URL; ?>/register.php" class="d-inline-flex align-items-center btn btn-warning btn-lg px-4 rounded-pill">
                Start Your Journey
            </a>
        </div>
    </div>

    <section class="features-section py-5">
        <h2 class="text-center text-warning display-5 fw-bold mb-5">Why Choose KP Fitness?</h2>
        <div class="row gx-4 gy-4">
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-calendar-alt"></i></div>
                        <h3 class="card-title h4">Smart Booking System</h3>
                        <p class="card-text">Our advanced reservation system allows you to book classes in real-time, manage your schedule, and never miss a session.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-robot"></i></div>
                        <h3 class="card-title h4">AI Workout Planner</h3>
                        <p class="card-text">Get personalized workout plans generated by our AI system based on your fitness level, goals, and body metrics.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-certificate"></i></div>
                        <h3 class="card-title h4">Expert Trainers</h3>
                        <p class="card-text">Learn from certified fitness professionals who provide personalized guidance and support throughout your journey.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="cta-section text-center p-5 bg-light rounded-3">
        <h2 class="text-dark display-5 fw-bold mb-3">Ready to Get Started?</h2>
        <p class="fs-5 text-muted mb-4">Your fitness transformation is just a click away.</p>
        <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-warning btn-lg px-4 rounded-pill">Join Now</a>
    </section>
</div>

<?php include 'includes/footer.php'; ?>
