<?php
define('PAGE_TITLE', 'Welcome');
require_once 'includes/config.php';
include 'includes/header.php';
?>

<style>
    .hero {
        background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=2575&auto=format&fit=crop') no-repeat center center/cover;
        color: white;
    }
    /* Original Orange Chatbot styles */
    .chatbot-bubble {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 1000;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background-color: #ff8c00; /* Orange */
        color: white;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.8rem;
        cursor: pointer;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        transition: transform 0.2s ease-in-out;
    }
    .chatbot-bubble:hover {
        transform: scale(1.05);
    }
    .chatbot-window {
        position: fixed;
        bottom: 90px;
        right: 20px;
        z-index: 1000;
        width: 350px;
        height: 450px;
        background-color: white;
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        display: flex;
        flex-direction: column;
        overflow: hidden;
    }
    .chatbot-header {
        background-color: #ff8c00; /* Orange */
        color: white;
        padding: 15px;
        font-size: 1.1rem;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .chatbot-messages {
        flex-grow: 1;
        padding: 15px;
        overflow-y: auto;
        background-color: #f9f9f9;
        display: flex;
        flex-direction: column;
    }
    .chatbot-input-area {
        padding: 10px 15px;
        background-color: #f1f1f1;
        display: flex;
    }
    .chatbot-input-area input {
        flex-grow: 1;
        border: 1px solid #ddd;
        border-radius: 20px;
        padding: 8px 15px;
        margin-right: 10px;
    }
    .chatbot-input-area button {
        background-color: #ff8c00; /* Orange */
        color: white;
        border: none;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .message {
        margin-bottom: 10px;
        padding: 8px 12px;
        border-radius: 8px;
        max-width: 80%;
    }
    .message.user {
        background-color: #ff8c00; /* Orange */
        color: white;
        align-self: flex-end;
        margin-left: auto;
    }
    .message.bot {
        background-color: #e2e2e2;
        color: #333;
        align-self: flex-start;
        margin-right: auto;
    }
</style>

<div class="container my-5">
    <div class="p-5 text-center rounded-3 hero">
        <h1 class="text-warning display-4 fw-bold">Unlock Your Inner Strength</h1>
        <p class="col-lg-8 mx-auto fs-5 text-light">
            Join KP Fitness and transform your fitness journey with our comprehensive class reservation system, expert trainers, and state-of-the-art facilities.
        </p>
        <div class="d-inline-flex gap-2 mb-5">
            <a href="<?php echo SITE_URL; ?>/register.php" class="d-inline-flex align-items-center btn btn-warning btn-lg px-4 rounded-pill">
                Start Your Journey
            </a>
        </div>
    </div>

    <section class="features-section py-5">
        <h2 class="text-center text-warning display-5 fw-bold mb-5">Why Choose KP Fitness?</h2>
        <div class="row gx-4 gy-4">
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-calendar-alt"></i></div>
                        <h3 class="card-title h4">Smart Booking System</h3>
                        <p class="card-text">Our advanced reservation system allows you to book classes in real-time, manage your schedule, and never miss a session.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-robot"></i></div>
                        <h3 class="card-title h4">AI Workout Planner</h3>
                        <p class="card-text">Get personalized workout plans generated by our AI system based on your fitness level, goals, and body metrics.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 text-center">
                    <div class="card-body">
                        <div class="feature-icon display-3 text-warning mb-3"><i class="fas fa-certificate"></i></div>
                        <h3 class="card-title h4">Expert Trainers</h3>
                        <p class="card-text">Learn from certified fitness professionals who provide personalized guidance and support throughout your journey.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="cta-section text-center p-5 card">
        <h2 class="text-warning display-5 fw-bold mb-3">Ready to Get Started?</h2>
        <p class="fs-5 text-light mb-4">Your fitness transformation is just a click away.</p>
        <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-warning btn-lg px-4 rounded-pill">Join Now</a>
    </section>

    <section class="get-in-touch-section py-5">
        <h2 class="text-center text-warning display-5 fw-bold mb-5">Get in Touch</h2>
        <div class="row text-center">
            <div class="col-md-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <i class="fas fa-phone fs-1 text-warning mb-3"></i>
                        <h5 class="card-title">Business Contact</h5>
                        <p class="card-text">Add later</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <i class="fas fa-envelope fs-1 text-warning mb-3"></i>
                        <h5 class="card-title">Email</h5>
                        <p class="card-text">Add later</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <i class="fas fa-map-marker-alt fs-1 text-warning mb-3"></i>
                        <h5 class="card-title">Address</h5>
                        <p class="card-text">123, Proto Street, Kota Kinabalu, Sabah</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Chatbot Bubble -->
<div class="chatbot-bubble" id="chatbot-bubble">
    <i class="fas fa-comments"></i>
</div>

<!-- Chatbot Window -->
<div class="chatbot-window d-none" id="chatbot-window">
    <div class="chatbot-header">
        <span>KP Fitness Bot</span>
        <i class="fas fa-times" id="chatbot-close" style="cursor: pointer;"></i>
    </div>
    <div class="chatbot-messages" id="chatbot-messages">
        <div class="message bot">Hello! How can I help you today?</div>
    </div>
    <div class="chatbot-input-area">
        <input type="text" id="chatbot-input" placeholder="Type your message...">
        <button id="chatbot-send"><i class="fas fa-paper-plane"></i></button>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {
    const chatbotBubble = document.getElementById('chatbot-bubble');
    const chatbotWindow = document.getElementById('chatbot-window');
    const chatbotClose = document.getElementById('chatbot-close');
    const chatbotMessages = document.getElementById('chatbot-messages');
    const chatbotInput = document.getElementById('chatbot-input');
    const chatbotSend = document.getElementById('chatbot-send');

    chatbotBubble.addEventListener('click', () => {
        chatbotWindow.classList.toggle('d-none');
    });

    chatbotClose.addEventListener('click', () => {
        chatbotWindow.classList.add('d-none');
    });

    chatbotSend.addEventListener('click', sendMessage);
    chatbotInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            sendMessage();
        }
    });

    function sendMessage() {
        const userMessage = chatbotInput.value.trim();
        if (userMessage === '') return;

        appendMessage(userMessage, 'user');
        chatbotInput.value = '';
        
        // Send message to chatbot API
        const formData = new FormData();
        formData.append('message', userMessage);

        fetch('api/chatbot_handler.php', {
            method: 'POST',
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            appendMessage(data.reply, 'bot');
            chatbotMessages.scrollTop = chatbotMessages.scrollHeight;
        })
        .catch(error => {
            console.error('Error:', error);
            appendMessage("Oops! Something went wrong. Please try again later.", 'bot');
            chatbotMessages.scrollTop = chatbotMessages.scrollHeight;
        });
    }

    function appendMessage(text, sender) {
        const messageDiv = document.createElement('div');
        messageDiv.classList.add('message', sender);
        messageDiv.innerHTML = text; // Use innerHTML to allow for links
        chatbotMessages.appendChild(messageDiv);
        chatbotMessages.scrollTop = chatbotMessages.scrollHeight;
    }
});
</script>

<?php include 'includes/footer.php'; ?>
