<?php
define('PAGE_TITLE', 'Welcome');
require_once 'includes/config.php';
include 'includes/header.php';
?>

<style>
    .hero {
        text-align: center;
        padding: 6rem 2rem;
        background: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=2575&auto=format&fit=crop') no-repeat center center/cover;
        border-radius: 12px;
        margin-top: 2rem;
    }
    .hero h1 {
        font-size: 3.5rem;
        font-weight: 800;
        color: var(--primary-color);
        margin-bottom: 1rem;
    }
    .hero p {
        font-size: 1.25rem;
        color: var(--text-dark);
        max-width: 700px;
        margin: 0 auto 2rem auto;
    }
    
    .features-section {
        padding: 4rem 0;
    }
    .section-title {
        text-align: center;
        font-size: 2.5rem;
        font-weight: 700;
        color: var(--primary-color);
        margin-bottom: 3rem;
    }
    .features-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
        gap: 2rem;
    }
    .feature-card {
        background: var(--light-bg);
        border: 1px solid var(--border-color);
        border-radius: 12px;
        padding: 2rem;
        text-align: center;
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    .feature-card:hover {
        transform: translateY(-10px);
        box-shadow: 0 15px 30px rgba(0,0,0,0.3);
    }
    .feature-icon {
        font-size: 3rem;
        color: var(--primary-color);
        margin-bottom: 1.5rem;
    }
    .feature-card h3 {
        font-size: 1.5rem;
        margin-bottom: 1rem;
    }
    .feature-card p {
        color: var(--text-dark);
    }
    
    .cta-section {
        background: var(--light-bg);
        border: 1px solid var(--border-color);
        border-radius: 12px;
        padding: 4rem 2rem;
        text-align: center;
        margin: 2rem 0;
    }
</style>

<div class="hero">
    <h1>Unlock Your Inner Strength</h1>
    <p>Join KP Fitness and transform your fitness journey with our comprehensive class reservation system, expert trainers, and state-of-the-art facilities.</p>
    <div>
        <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-primary" style="font-size: 1.1rem; padding: 1rem 2rem;">Start Your Journey</a>
    </div>
</div>

<section class="features-section">
    <h2 class="section-title">Why Choose KP Fitness?</h2>
    <div class="features-grid">
        <div class="feature-card">
            <div class="feature-icon"><i class="fas fa-calendar-alt"></i></div>
            <h3>Smart Booking System</h3>
            <p>Our advanced reservation system allows you to book classes in real-time, manage your schedule, and never miss a session.</p>
        </div>
        <div class="feature-card">
            <div class="feature-icon"><i class="fas fa-robot"></i></div>
            <h3>AI Workout Planner</h3>
            <p>Get personalized workout plans generated by our AI system based on your fitness level, goals, and body metrics.</p>
        </div>
        <div class="feature-card">
            <div class="feature-icon"><i class="fas fa-certificate"></i></div>
            <h3>Expert Trainers</h3>
            <p>Learn from certified fitness professionals who provide personalized guidance and support throughout your journey.</p>
        </div>
    </div>
</section>

<section class="cta-section">
    <h2 class="section-title" style="margin-bottom: 1rem;">Ready to Get Started?</h2>
    <p style="font-size: 1.1rem; color: var(--text-dark); margin-bottom: 2rem;">Your fitness transformation is just a click away.</p>
    <a href="<?php echo SITE_URL; ?>/register.php" class="btn btn-primary" style="font-size: 1.1rem; padding: 1rem 2rem;">Join Now</a>
</section>

<?php include 'includes/footer.php'; ?>
